# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [108]:
N = int(input("Введите N: "))

N_list = list(reversed(range(0, N)))
N_massive = np.array(N_list)

print(N_massive, type(N_massive))

Введите N: 10
[9 8 7 6 5 4 3 2 1 0] <class 'numpy.ndarray'>


# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [109]:
x = np.diag(N_massive+1)
print(x)
print('Сумма значений по диагонали:', np.sum(x))

[[10  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  1]]
Сумма значений по диагонали: 55


# Задание 3
                Решите систему уравнений:
                    4x + 2y + z = 4
                    x + 3y = 12
                    5y + 4z = -3

In [39]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] ) # коэфф. при переменных в левой части
b = np.array( [4, 12, -3] )                         # правая часть

In [40]:
from numpy import linalg

In [43]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [44]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )  # проверка


True

# Задача 4 
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - 
количество покупок категорий товаров этим пользователем. Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [46]:
import matplotlib.pyplot as plt

In [45]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [98]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [111]:
next_user_stats_Length = np.linalg.norm(next_user_stats) # длина вектора 

users_stats_Length = []
    
for i in users_stats:
    users_stats_Length.append(np.linalg.norm(i)) # считаем вектор для каждой строки и записываем в список
    print (np.dot( i, next_user_stats ) / (next_user_stats_Length * np.linalg.norm(i) ))   


0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
